### ISSUE TITLE
[Feature Request] Add dynamic Subject-IDs

### ISSUE THREAD

**Issue by generationmake** [107-systems/107-Arduino-Cyphal#163]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### ⚡ Feature Request

**Please Describe The Problem To Be Solved**
Subject-IDs should be dynamic so that a node can be configured and allow system integration.

**Comment by aentinger** [comment]
This has been under work at some point in time in https://github.com/107-systems/107-Arduino-Cyphal/pull/137 and would be needed to be picked up again.
