### ISSUE TITLE
[Feature Request] Remodel API to emulate ROS publish/subscribe APIs

### ISSUE THREAD

**Issue by aentinger** [107-systems/107-Arduino-Cyphal#174]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### ⚡ Feature Request

Doing so would simplify the internal logic of `Node`.

```C++
auto heartbeat_pub = node_hdl.create_publisher<uavcan::node::Heartbeat>(/* to be defined */);
heartbeat_pub.publish(heartbeat_msg);
```

```C++
auto heartbeat_sub = node_hdl.::create_subscription<uavcan::node::Heartbeat>(/* to be defined */);
```

**Comment by pavel-kirienko** [comment]
This is especially interesting for subscribers because it allows you to implement type erasure on the callback, thus allowing the customer to pass arbitrary functions/lambdas as handlers.

**Comment by aentinger** [comment]
Lambdas are the plan :grin: . If there some specific API you are thinking of, feel free to propose it.
