### ISSUE TITLE
Fix UniqueId for ATSAME5x

### ISSUE THREAD

**Issue by generationmake** [107-systems/107-Arduino-Cyphal#189]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### :bug: Bug Report

I think UniqueId does not work with ATSAME5x (https://www.adafruit.com/product/4759).
I think it goes into ARDUINO_ARCH_SAMD but there is nothing defined for ATSAME5x.

**Comment by aentinger** [comment]
A very quick and dirty fix, try changing this [line](https://github.com/107-systems/107-Arduino-Cyphal/blob/main/src/utility/UniqueId16-samd.cpp#L14):

```diff
-#ifdef ARDUINO_ARCH_SAMD
+#if defined(ARDUINO_ARCH_SAMD) || defined(ARDUINO_SAMD_ADAFRUIT)
```

**Comment by aentinger** [comment]
And also this [line](https://github.com/107-systems/107-Arduino-Cyphal/blob/main/src/utility/UniqueId16.cpp#L27) accordingly.

**Comment by generationmake** [comment]
hi @aentinger 
it seems like it is more a problem with this line: https://github.com/107-systems/107-Arduino-Cyphal/blob/main/src/utility/UniqueId16.h#L38

**Comment by aentinger** [comment]
Done @generationmake :heavy_check_mark: :wink:
