### ISSUE TITLE
Cannot compile;  fatal error: span: No such file or directory

### ISSUE THREAD

**Issue by walnut-engineering** [107-systems/107-Arduino-Cyphal#240]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### :bug: fatal error: span: No such file or directory

**Describe the bug**

Cannot compile in VSCODE or Arduino IDE.  Google search seems to indicate compiler mismatch between Cyphal library and esp32-arduino toolchain.. but I am not paid for my programming skills.

The library looks to be supported according to https://forum.opencyphal.org/t/107-arduino-uavcan-with-esp32/1096 however that post is a couple years old and something may have changed.

**Minimum example code to replicate the bug**
```C++
#include <107-Arduino-Cyphal.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}
```

**Minimum configuration to replicate the bug**
Please provide the configuration data used to build your application:
* Build Toolchain: (Arduino IDE @ 2.1.1)
* Arduino Core: (sp32 @ 2.0.11 )
* Library Version: (107-Arduino-Cyphal @ 3.2.1)

**Comment by aentinger** [comment]
Yes, ESP32 support was dropped because arduino-esp32 does not support C++17 which is a must-have requirement.
