### ISSUE TITLE
Add the ability to prioritize sending messages

### ISSUE THREAD

**Issue by bakul14** [107-systems/107-Arduino-Cyphal#276]
<a href="https://107-systems.org/"><img align="right" src="https://raw.githubusercontent.com/107-systems/.github/main/logo/107-systems.png" width="15%"></a>

### ⚡ Feature Request

It is necessary to implement setting the priority subject and service messages, since this feature is **available in libcanard**.
Here is a piece of implementation of the publish(T const & msg) method. Priority is not a parameter and it is set to `CanardPriorityNominal`.
```bash
template<typename T>
bool Publisher<T>::publish(T const & msg)
{
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"
  CanardTransferMetadata const transfer_metadata =
  {
   .priority       = CanardPriorityNominal,
    .transfer_kind  = CanardTransferKindMessage,
    .port_id        = _port_id,
    .remote_node_id = CANARD_NODE_ID_UNSET,
    .transfer_id    = _transfer_id++,
  };
#pragma GCC diagnostic pop
```

There are 2 possible solutions:
1) Add the ability to set priority through the publisher/subscriber/client/server constructor.
2) Pass priority as a parameter to the publish() method and others.

**Comment by aentinger** [comment]
I am willing to merge a high quality pull request providing this functionality using the first approach.

**Comment by bakul14** [comment]
Okay, it's good. I am ready to check your PR

**Comment by aentinger** [comment]
I am willing to receive your PR ;)

**Comment by pavel-kirienko** [comment]
@bakul14 that's not how it works. You need to fork this repository, push your changes there, then send a pull request: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request

![image](https://github.com/107-systems/107-Arduino-Cyphal/assets/3298404/603792b5-347a-40a8-be8b-541a21263105)
