### ISSUE TITLE
Update keywords.txt with freshly added types

### ISSUE THREAD

**Issue by aentinger** [107-systems/107-Arduino-Cyphal#92]
Both namespaces and classes.

**Comment by aentinger** [comment]
Hell, maybe someone could write a tool perusing all the wrappers and extracting all namespaces and classes.

**Comment by per1234** [comment]
I have collected a list of potential tools here: https://github.com/per1234/arduino-ci-script/issues/17
Never got around to looking into it closely though.

**Comment by aentinger** [comment]
That would be terrific if one of those tools could be repurposed! :100:

**Comment by aentinger** [comment]
After mediating on it I believe this is no longer relevant. There are simply too much types and the benefit is rather minimal.
